### ISSUE TITLE
Incorrect action url in README

### ISSUE THREAD

**Issue by senkevichdv** [jpb06/jest-badges-action#13]
Hello. Thanks for such amazing action! I found that I can not use
```
uses: actions/jest-badges-action@latest
```
however I was able to use this action via
```
uses: jpb06/jest-badges-action@v1.8.0
```
Is it expected?

**Comment by jpb06** [comment]
Hello! 

that's unexpected. I thought [at]latest would automatically point to the last version of the action. 

Thank you for reporting this, I will investigate.

**Comment by senkevichdv** [comment]
Thanks for quick response. But also please notice that I was not able to use `uses: actions/` (prefix of your action name) -> it was not found, but with your name as a prefix (`jpb06/`) it worked great.

**Comment by jpb06** [comment]
Good catch!

This mistake is also present in the readme of this action:
https://github.com/jpb06/bump-package

**Comment by jpb06** [comment]
Should be good now. Sorry about the inconvenience.
