### ISSUE TITLE
How to use the badge in the readme of a repository

### ISSUE THREAD

**Issue by drikusroor** [jpb06/jest-badges-action#34]
Perhaps I'm missing something as I'm not a Github Actions badge expert, but what would be the url(s) of the coverage badges that are generated by this Github action? And could an example be added to the readme of this project?

**Comment by jpb06** [comment]
Hello.

Badges are generated as `svg` files and pushed directly to the repo, [like here](https://github.com/jpb06/jest-badges-action/tree/master/badges).

They are generated only when the action is ran against the `master` or `main` branch though. You can tweak this with the `branches` param like this:

```
[...]
- name: Generating coverage badges
  uses: jpb06/jest-badges-action@latest
    with:
      // Badges will be generated when action is ran on `master`, `preprod` and `staging` branch.
      branches: master,preprod,staging
```

**Comment by jpb06** [comment]
https://github.com/jpb06/jest-badges-action/pull/35

**Comment by jpb06** [comment]
I added an example for the badges generated and how to use them in a readme, for clarity:
https://github.com/jpb06/jest-badges-action/blob/improving-readme/README.md

**Comment by drikusroor** [comment]
Thanks! ❤️
