### ISSUE TITLE
Git commit/push only on changes

### ISSUE THREAD

**Issue by YunaBraska** [jpb06/jest-badges-action#41]
Hi and thanks for the awesome github action :)

Error:
```
/usr/local/bin/git push
To https://github.com/YunaBraska/java-info-action
 ! [rejected]        docs/coverage_badge -> docs/coverage_badge (fetch first)
error: failed to push some refs to 'https://github.com/YunaBraska/java-info-action'
Error: 🔶 Oh no! An error occured: The process '/usr/local/bin/git' failed with exit code 1
```

Reason:
> I have a multi matrix pipeline. The first run is pushing the result and the second run is having an issue in pushing the result again which is not even neccessary. The file should not have been changed.

MywWish's:
> * 1 Please make git only push on changes
> * 2 Please let me define the commit message and commit user
> * 3 Make git commit & push optional - so that i handle things by my self e.g only add one specific svg or commit more tha none changes in a workflow run at once
> * 4 Let me define the output folder for myself
> * 5 use the current branch `${{ github.ref_name || github.head_ref }}` as default `branches` as default branches like `main` or `master` are usually protected. Its not a good prectice to change the main with a insecure workflow run.

**Comment by jpb06** [comment]
Hello!

Sorry, didn't have time to take a look just yet; Christmas celebrations and all.

I wil have a look this week 🙇🏻

**Comment by YunaBraska** [comment]
No worries :) Thank you and happy christmas time

**Comment by jpb06** [comment]
Hey. Thank you for opening this issue 🙇🏻
Let's get into it!

> 1 Please make git only push on changes

I'm not certain about the use case here. Right now what this action does is doing a `git diff` on badges already committed, so if you delete them like [here](https://github.com/YunaBraska/java-info-action/pull/9) they will always come back (as it is the point of this action to create badges anyway. So I'm not sure of what to make of this.

> 2 Please let me define the commit message and commit user

Should be covered by #42. You can already use a custom commit message using [`commit-message`](https://github.com/jpb06/jest-badges-action#-commit-message) input.

> 3 Make git commit & push optional - so that i handle things by my self e.g only add one specific svg or commit more tha none changes in a workflow run at once

Sure thing, can do. Will open a PR for that.

> 4 Let me define the output folder for myself

ditto.

> 5 use the current branch ${{ github.ref_name || github.head_ref }} as default branches as default branches like main or master are usually protected. It's not a good prectice to change the main with an insecure workflow run.

You're right that's an issue. The rational behind it is I wouldn't want my PR to be polluted by generated stuff as it would distract reviewers. And we only need badges on the perpetual branches anyway. A workaround could be to push them to another perpetual branch that isn't protected and is not reflecting staging or production state.

So again I'm not sure what to make of this 🫤
What do you think about it?

**Comment by YunaBraska** [comment]
> "Right now what this action does is doing a git diff on badges already committed"
Ah okay, on a multi OS pipeline you might need to do git pull before checking the diff. 
But maybe its just an edge case which is easy to get as your GHA might have to much functionallity.
There are GHA's for git already. 
For me its fine when i can handle git by my self, then everything is solved for me. I just need the created badges ;) 
You have my star for your GHA ;) I like your work. Thnak you.

**Comment by jpb06** [comment]
Thank you. There is the custom output folder option to add yet and it should be O.K then 💯

**Comment by jpb06** [comment]
https://github.com/jpb06/jest-badges-action/releases

Point 2 & 3 released. Let me know if something is amiss.
